{{
    config(
        materialized='table'
    )
}}
SELECT 40000+row_number() OVER (ORDER BY ID) AS USER_KEY,ID AS USER_ID,USERNAME AS USER_NAME,EMAIL,FIRSTNAME,LASTNAME,DBT_VALID_FROM
         AS EFFECTIVE_FROM ,DBT_VALID_TO AS EFFECTIVE_TO,
         (CASE WHEN DBT_VALID_TO IS NULL THEN 'TRUE' ELSE 'FALSE' END) AS STATUS
          FROM  {{ source("ref_SCD2", "SCD2_USER_SNAPSHOT") }} 